FROM openjdk:8
EXPOSE 8080
ADD target/spring-boot-cicd-jenkins-docker-0.0.1-SNAPSHOT.jar spring-boot-cicd-jenkins-docker-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "spring-boot-cicd-jenkins-docker-0.0.1-SNAPSHOT.jar"]
